DELETE http://localhost:3003/api/blogs/663d23809c5eb44c49d2b666
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Im1pYW1vcmVsdmlyYSIsImlkIjoiNjYzNjg5ZDJiNzU1NmM1NWNkNmUzNTVhIiwiaWF0IjoxNzE1MjgyNzkyfQ.evm2qfI9bhODpDQ-vBaj4NbAHY3RFhacxEAXcS1RWB8